teleop_node:
  ros__parameters:
    
    axis_linear:  # Left thumb stick vertical
      x: 1
      y: 0
    scale_linear:
      x: 0.5
      y: 0.5
    scale_linear_turbo:
      x: 1.0
      y: 1.0

    axis_angular:  # Left thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: 1.0
    scale_angular_turbo:
      yaw: 1.5

    require_enable_button: false
    enable_button: 6  # Left shoulder button
    enable_turbo_button: 7  # Right shoulder button